import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body
//         style={{
//           margin: 0,
//           fontFamily: "system-ui, Arial",
//           background: "#f5f6f8",
//         }}
//       >
//         <header
//           style={{
//             background: "#111",
//             color: "white",
//             padding: "16px 40px",
//             fontWeight: "bold",
//           }}
//         >
//           Privacy Policy
//         </header>

//         <main
//           style={{
//             display: "flex",
//             justifyContent: "center",
//             padding: "40px",
//           }}
//         >
//           {children}
//         </main>

//         <footer
//           style={{
//             textAlign: "center",
//             padding: "20px",
//             fontSize: "14px",
//             color: "#666",
//           }}
//         >
//           © 2026 Developer
//         </footer>
//       </body>
//     </html>
//   )
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        style={{
          margin: 0,
          fontFamily: "system-ui, Arial",
          background: "#f5f6f8",
          color: "#1f2937"
        }}
      >
        <header
          style={{
            background: "#111",
            color: "white",
            padding: "16px 40px",
            fontWeight: "bold",
          }}
        >
          Privacy Policy
        </header>

        <main
          style={{
            display: "flex",
            justifyContent: "center",
            padding: "40px",
          }}
        >
          {children}
        </main>

        <footer
          style={{
            textAlign: "center",
            padding: "20px",
            fontSize: "14px",
            color: "#6b7280",
          }}
        >
          © 2026 Developer
        </footer>
      </body>
    </html>
  )
}
